package com.lanou3g.autohome;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lanou3g.autohome.collection;

import com.lanou3g.autohome.collectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDaoConfig;

    private final collectionDao collectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDaoConfig = daoConfigMap.get(collectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        collectionDao = new collectionDao(collectionDaoConfig, this);

        registerDao(collection.class, collectionDao);
    }
    
    public void clear() {
        collectionDaoConfig.clearIdentityScope();
    }

    public collectionDao getCollectionDao() {
        return collectionDao;
    }

}
